services:
  web:
    build:
      context: .
    container_name: django_web
    volumes:
      - .:/code
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"     # ホストの8080番ポートをコンテナの80番ポートにマッピング
      - "8443:443"   # ホストの8443番ポートをコンテナの443番ポートにマッピング
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/code
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/private/djartipy:/etc/nginx/ssl:ro
      - ./certbot:/var/www/certbot
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ssl: