version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"     # 標準HTTPポート
      - "443:443"   # 標準HTTPSポート
      - "8081:80"   # 開発環境用
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/code
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/private/djartipy:/etc/nginx/ssl:ro
      - ./certbot:/var/www/certbot
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  ssl: