services:
  web:
    build:
      context: .
    container_name: django_web
    volumes:
      - .:/code
    expose:
      - "8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - .:/code
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
