# Generated by Django 4.2.16 on 2024-11-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='scores/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_tracks/')),
            ],
        ),
    ]
