# Generated by Django 4.2.16 on 2024-11-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='page_start_times',
            field=models.JSONField(default=dict, help_text='各ページの開始時間（秒単位）を保存する辞書'),
        ),
    ]
